name: PR Comment hook

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump GitHub context
      id: trigger
#      env:
#        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo ::set-output name=cmd::${{ github.event.comment.body }}
        echo ::set-output name=pr_url::${{ github.event.issue.pull_request.url }}

    - name: Check output
      if: steps.trigger.outputs.cmd == 'deploy'
      run: |
        echo cmd is deploy
        
        pr_context=`curl https://api.github.com/repos/somen440/zatsu/pulls/5`
        pr_branch=`echo ${pr_context} | jq '.head.ref'`
        pr_number=`echo ${pr_context} | jq '.number'`
        pr_label=`echo ${pr_context} | jq '.head.label'`
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b dev origin/dev

        for file in `git diff --name-only origin/dev origin/${pr_branch}`
        do
          echo file is $file
          git checkout $file -- origin/${pr_branch}
        done

        git add .
        git commit -m "update dev from #${pr_number} ${pr_label}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
