name: PR Comment hook

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dump GitHub context
      id: trigger
#      env:
#        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo ::set-output name=cmd::${{ github.event.comment.body }}
        echo ::set-output name=pr_url::${{ github.event.issue.pull_request.url }}

    - name: Commit
      if: steps.trigger.outputs.cmd == 'deploy'
      run: |
        echo cmd is deploy
        
        pr_context=`curl ${{ steps.trigger.outputs.pr_url }}`
        pr_branch=`echo ${pr_context} | jq '.head.ref' --raw-output`
        pr_number=`echo ${pr_context} | jq '.number' --raw-output`
        pr_label=`echo ${pr_context} | jq '.head.label' --raw-output`
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --prune
        git checkout -b dev origin/dev

        for file in `git diff --name-only origin/dev origin/${pr_branch}`
        do
          echo file is $file
          git checkout origin/${pr_branch} -- $file
        done

        git add .
        git commit -m "update dev from #${pr_number} ${pr_label}"

    - name: Push changes
      if: steps.trigger.outputs.cmd == 'deploy'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
