name: PR Comment hook

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      id: trigger
#      env:
#        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo ::set-output name=cmd::${{ github.event.comment.body }}
        echo ::set-output name=pr_url::${{ github.event.issue.pull_request.url }}

    - name: Check output
      if: steps.trigger.outputs.cmd == 'deploy'
      run: echo cmd is deploy
