name: Golang E2E

on:
  pull_request:
    brances:
    - master

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3333:3306
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: mysql -uroot -proot --host 127.0.0.1 -P 3333 test_db < golang/e2e/docker-entrypoint-initdb.d/initdb.sql

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'

    - name: Install
      working-directory: ./golang/e2e
      run: go mod download

    - name: Test
      working-directory: ./golang/e2e
      run: go test -v
      env:
        HOST: 127.0.0.1
        PORT: 3333
        USER: root
        PASSWORD: root
        DATABASE: test_db
        CGO_ENABLED: 0
