name: Golang E2E

on:
  pull_request:
    brances:
    - master

jobs:
  e2e:
    runs-on: ubuntu-latest

    container:
      image: golang:1.13

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        # volumes:
        #   - golang/e2e/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify MySQL connection
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done

    - name: Setup
      run: mysql -uroot -proot test_db < golang/e2e/docker-entrypoint-initdb.d/initdb.sql

    - name: Install
      working-directory: ./golang/e2e
      run: go mod download

    - name: Test
      working-directory: ./golang/e2e
      run: go test -v
      env:
        HOST: mysql
        PORT: 3306
        USER: root
        PASSWORD: root
        DATABASE: test_db
        CGO_ENABLED: 0
